### ISSUE TITLE
Question: How the OTA mechanism works?

### ISSUE THREAD

**Issue by peros550** [maccoylton/esp-homekit-sonoff-basic#1]
Many thanks for your efforts in this project. 

How exactly would the OTA mechanism works? Just the basic steps. 

Thanks,

**Comment by maccoylton** [comment]
Added a Wiki Page, check it out and let me know how you get on

**Comment by xfce** [comment]
Hi, 
    if i just want to upgrade the firmware in the my local PC with local network, it means just use wireless to upgrade firmware, (usually the OTA is just no wire) can this work, or is there some simple guide? thanks

**Comment by maccoylton** [comment]
If you want to do a quick upgrade by flashing directly, then use something likes this:- 

esptool.py -p /dev/cu.usbserial erase_flash esptool.py -p /dev/cu.usbserial --baud 230400 write_flash -fs 8m -fm qio -ff 40m 0x2000 main.bin

Let me know how you get on

**Comment by xfce** [comment]
Hi
   I just follow your wiki guide, flash my ESP8266 as the stage 1, but when move to stage 2, I can't find any AP name for ESP8266 , also I have test my ESP8266, when flash other firmware, it is OK

**Comment by maccoylton** [comment]
Can you upload the log please and I'll take a look

**Comment by maccoylton** [comment]
assume issue is resolved, if not please upload log and I'll take a look
