### ISSUE TITLE
always reboot

### ISSUE THREAD

**Issue by kiralikbeyin** [maccoylton/esp-homekit-sonoff-basic#2]
https://github.com/maximkulkin/esp-homekit-demo/issues/97

**Comment by kiralikbeyin** [comment]
hmm please update wiki

enter the GitHub directory - maccoylton/eps-homekit-sonoff-basic
to
enter the GitHub directory - maccoylton/ESP-homekit-sonoff-basic

**Comment by maccoylton** [comment]
Wiki updated
