### ISSUE TITLE
Question and request.

### ISSUE THREAD

**Issue by toshibochan** [maccoylton/esp-homekit-sonoff-basic#3]
Thank you for all the HomeKit firmware you making and share to everyone.
I have question and request.
I was able to install your firmware in sonoff-basic. Work great but I want ask. Is the led light supposed turning ON and OFF all the time? If it is can make to turn on only when light is on? Because in the night the green light is very strong in the bedroom. Maybe can add toggle switch in the app to do?

**Comment by maccoylton** [comment]
>Thank you for all the HomeKit firmware you making and share to everyone. ...

@toshibochan the light will be on if the switch is on, the light will toggle periodically to indicate Wi-Fi is connected. One flash is good, four flashes means the Wi-Fi is disconnected. If you don’t want the led to toggle, then set the Wi-Fi check interval to 0. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by toshibochan** [comment]
how to clone your repository to my GitHub?

**Comment by maccoylton** [comment]
Just do a fork

**Comment by toshibochan** [comment]
Fork worked thanks!!!!

**Comment by maccoylton** [comment]
yw :-)

**Comment by toshibochan** [comment]
> > Thank you for all the HomeKit firmware you making and share to everyone. ...
> 
> @toshibochan the light will be on if the switch is on, the light will toggle periodically to indicate Wi-Fi is connected. One flash is good, four flashes means the Wi-Fi is disconnected. If you don’t want the led to toggle, then set the Wi-Fi check interval to 0.
> 
> Sent with [GitHawk](http://githawk.com)

I did set 10 to 0
homekit_characteristic_t wifi_check_interval   = HOMEKIT_CHARACTERISTIC_(CUSTOM_WIFI_CHECK_INTERVAL, 10, .setter=wifi_check_interval_set);
to
homekit_characteristic_t wifi_check_interval   = HOMEKIT_CHARACTERISTIC_(CUSTOM_WIFI_CHECK_INTERVAL, 0, .setter=wifi_check_interval_set);

But now on log give me this over and over and over:

checkWifiTask : no check performed Free Heap=31108, Free Stack=15

**Comment by toshibochan** [comment]
This message "checkWifiTask : no check performed Free Heap=31108, Free Stack=15" not going to over load the esp memory?

**Comment by toshibochan** [comment]
is the why to this message not print when do Wi-Fi check interval to 0?

**Comment by maccoylton** [comment]
That's a bug, I'll take look tonight and fix it. I appreciate all your feedback :-)

**Comment by toshibochan** [comment]
Cool thanks
