### ISSUE TITLE
how to build main.bin main.bin.sig?

### ISSUE THREAD

**Issue by toshibochan** [maccoylton/esp-homekit-sonoff-basic#4]
how to build main.bin main.bin.sig and upload to GitHub?
![Screen Shot 2020-01-03 at 11 45 27 AM](https://user-images.githubusercontent.com/15816913/71745416-e8ed8c00-2e1e-11ea-88c6-d13e609789b1.png)

**Comment by maccoylton** [comment]
in the src directory executing "make" will build the firmware and "make signature" will create the signature
