### ISSUE TITLE
error making

### ISSUE THREAD

**Issue by toshibochan** [maccoylton/esp-homekit-sonoff-basic#5]
/home/user/projects/esp-homekit-demo/esp-homekit-sonoff-basic/src/main.c:48:30: fatal error: shared_functions.h: No such file or directory
 #include <shared_functions.h>
                                                     ^

**Comment by maccoylton** [comment]
Did you execute git submodule update --init --recursive? The error is telling you it can't find the shared functions library, which should be in /home/user/projects/esp-homekit-demo/esp-homekit-sonoff-basic/components/esp-homekit-common-functions.

**Comment by toshibochan** [comment]
I did and everything is download except the shared_functions

**Comment by maccoylton** [comment]
Sorry that was my bad, it should work now

**Comment by toshibochan** [comment]
Yay I will try soon thanks!

**Comment by toshibochan** [comment]
still have error.
make -C src flash
build folder is ok but no have firmware folder.

LD build/main.out
./build/shared_functions.a(shared_functions.o):(.text.task_stats_task+0x1c): undefined reference to `uxTaskGetSystemState'
./build/shared_functions.a(shared_functions.o): In function `task_stats_task':
/home/user/projects/esp-homekit-sonoff-basic/components/esp-homekit-common-functions/shared_functions/shared_functions.c:241: undefined reference to `uxTaskGetSystemState'
collect2: error: ld returned 1 exit status
/home/user/projects/esp-open-rtos/common.mk:232: recipe for target 'build/main.out' failed
make: *** [build/main.out] Error 1
make: Leaving directory '/home/user/projects/esp-homekit-sonoff-basic/src'

**Comment by peros550** [comment]
I was able to overcome this issue by altering file FreeRTOSConfig.h which is inside ESP-OPEN-RTOS. 
If you placed this directory under your projects directory you will find the file at this path: 

/home/user/projects/esp-open-rtos/FreeRTOS/Source/include/FreeRTOSConfig.h

Go there and find parameter configUSE_TRACE_FACILITY and set to 1. It should now work for you.

**Comment by maccoylton** [comment]
Sorry, I didn't have time to test this  last night, I forgot to update the Makefile, just add that to the Makefile, and there is no need to updated FreeRTOS

EXTRA_CFLAGS += -DconfigUSE_TRACE_FACILITY

**Comment by maccoylton** [comment]
Add that to the Makefile and pushed
