### ISSUE TITLE
issue when lose internet connection

### ISSUE THREAD

**Issue by toshibochan** [maccoylton/esp-homekit-sonoff-basic#8]
when the device lose internet connection the device turn off.

**Comment by maccoylton** [comment]
The loss of internet causes the device to restart, this is an issue in  esp-open-rtos. I may be able to save the status each time it changes and the load that state after a restart

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by toshibochan** [comment]
This is problem or is design to reboot to tray reconnect to the network?

**Comment by maccoylton** [comment]
For me this is an issue in esp-open-rtos. The workaround I implemented above may help
